### ISSUE TITLE
#feature - 클라우드 파트 (컨테이너 상태 확인)

### ISSUE THREAD

**Issue by dhslrl321** [V-Ground/Backend#3]
# 컨테이너 상태 확인 API 추가하기

### Todos

- [x] AWS CLI Docs 확인
- [x] EcsUtil 에 코드 추가
- [x] service & controller 개발
- [x] Postman 업데이트
